// Comic metadata — sourced from comics-metadata.json
// YouTube URLs extracted from podcast transcripts + web search

export interface Comic {
  comic_id: string;
  slug: string;
  quote: string;
  speaker: string;
  episode_title: string;
  episode_file: string;
  youtube_url: string;
  timestamp: string;
  panels: number;
  theme: string;
  cover: string; // path to cover image (panel_1)
}

export const comics: Comic[] = [
  {
    comic_id: "comic_1",
    slug: "comic-1",
    quote: "Ship fast, iterate later.",
    speaker: "Reid Hoffman",
    episode_title: "Slack founder: Mental models for building products people love ft. Stewart Butterfield",
    episode_file: "stewart-butterfield.md",
    youtube_url: "https://www.youtube.com/watch?v=kLe-zy5r0Mk",
    timestamp: "00:00:14",
    panels: 4,
    theme: "Kitchen cooking metaphor — shipping products fast",
    cover: "/comics/comic_1/panel_1.webp",
  },
  {
    comic_id: "comic_2",
    slug: "comic-2",
    quote: "If you can't see limitless opportunities to improve, you shouldn't be designing the product.",
    speaker: "Stewart Butterfield",
    episode_title: "Slack founder: Mental models for building products people love ft. Stewart Butterfield",
    episode_file: "stewart-butterfield.md",
    youtube_url: "https://www.youtube.com/watch?v=kLe-zy5r0Mk",
    timestamp: "00:47:06",
    panels: 4,
    theme: "Woman at wardrobe — perfectionism and product craft",
    cover: "/comics/comic_2/panel_1.webp",
  },
  {
    comic_id: "comic_3",
    slug: "comic-3",
    quote: "AI is an amplifier. If you don't know what you're doing, you're just going to produce garbage faster.",
    speaker: "Lazar Jovanovic",
    episode_title: "The rise of the professional vibe coder | Lazar Jovanovic",
    episode_file: "lazar-jovanovic.md",
    youtube_url: "https://www.youtube.com/watch?v=0XNkUdzxiZI",
    timestamp: "00:57:03",
    panels: 4,
    theme: "Using phone for navigation — AI amplifying mistakes",
    cover: "/comics/comic_3/panel_1.webp",
  },
  {
    comic_id: "comic_4",
    slug: "comic-4",
    quote: "There's always data to show you that you won't be successful, but sometimes just be foolish and go ahead with it.",
    speaker: "Aishwarya Naresh Reganti",
    episode_title: "Why most AI products fail: Lessons from 50+ AI deployments | Aishwarya Naresh Reganti + Kiriti Badam",
    episode_file: "aishwarya-naresh-reganti--kiriti-badam.md",
    youtube_url: "https://www.youtube.com/watch?v=z7T1pCxgvlA",
    timestamp: "01:21:35",
    panels: 4,
    theme: "Character facing data/odds — being bold despite the numbers",
    cover: "/comics/comic_4/panel_1.webp",
  },
  {
    comic_id: "comic_5",
    slug: "comic-5",
    quote: "What matters is that the product works.",
    speaker: "Ben Horowitz",
    episode_title: "$46B of hard truths from Ben Horowitz",
    episode_file: "ben-horowitz.md",
    youtube_url: "https://www.youtube.com/watch?v=KPxTekxQjzc",
    timestamp: "00:48:39",
    panels: 4,
    theme: "Building/fixing — pragmatic product philosophy",
    cover: "/comics/comic_5/panel_1.webp",
  },
  {
    comic_id: "comic_6",
    slug: "comic-6",
    quote: "Everybody wants to talk about job loss, but what you want to look at is task loss.",
    speaker: "Marc Andreessen",
    episode_title: "Marc Andreessen: The real AI boom hasn't even started yet",
    episode_file: "marc-andreessen.md",
    youtube_url: "https://www.youtube.com/watch?v=87Pm0SGTtN8",
    timestamp: "00:39:28",
    panels: 4,
    theme: "Office scene — AI and jobs perspective",
    cover: "/comics/comic_6/panel_1.webp",
  },
  {
    comic_id: "comic_7",
    slug: "comic-7",
    quote: "The more mind-blowing it is, the more you should give it away for free.",
    speaker: "Lenny Rachitsky",
    episode_title: "Elena Verna 4.0",
    episode_file: "elena-verna-40.md",
    youtube_url: "https://www.youtube.com/watch?v=6qAB6aUMIeA",
    timestamp: "00:55:51",
    panels: 4,
    theme: "Generosity and growth — free product strategy",
    cover: "/comics/comic_7/panel_1.webp",
  },
  {
    comic_id: "comic_8",
    slug: "comic-8",
    quote: "Don't make it fake. If you don't love someone, don't tell them you love them.",
    speaker: "Jeetu Patel",
    episode_title: "AI is critical for humanity's survival | Jeetu Patel (Cisco President)",
    episode_file: "jeetu-patel.md",
    youtube_url: "https://www.youtube.com/watch?v=ylNKlBlkFas",
    timestamp: "01:02:19",
    panels: 4,
    theme: "Authenticity in relationships and product — keeping it real",
    cover: "/comics/comic_8/panel_1.webp",
  },
  {
    comic_id: "comic_9",
    slug: "comic-9",
    quote: "You should be embarrassed if your first version is not bad enough.",
    speaker: "Reid Hoffman (via Stewart Butterfield)",
    episode_title: "Slack founder: Mental models for building products people love ft. Stewart Butterfield",
    episode_file: "stewart-butterfield.md",
    youtube_url: "https://www.youtube.com/watch?v=kLe-zy5r0Mk",
    timestamp: "00:46:31",
    panels: 4,
    theme: "Perfectionism vs shipping — embracing imperfection",
    cover: "/comics/comic_9/panel_1.webp",
  },
  {
    comic_id: "comic_10",
    slug: "comic-10",
    quote: "The trick is get more people to try it, just ship things you can talk about.",
    speaker: "Lenny Rachitsky",
    episode_title: "Elena Verna 4.0",
    episode_file: "elena-verna-40.md",
    youtube_url: "https://www.youtube.com/watch?v=6qAB6aUMIeA",
    timestamp: "00:53:41",
    panels: 4,
    theme: "Growth strategy — shipping and talking about it",
    cover: "/comics/comic_10/panel_1.webp",
  },
  {
    comic_id: "comic_11",
    slug: "comic-11",
    quote: "We wanted a company where a thousand people could work, but it'll look like 10 people did it.",
    speaker: "Brian Chesky",
    episode_title: "Brian Chesky's new playbook",
    episode_file: "brian-chesky.md",
    youtube_url: "https://www.youtube.com/watch?v=4ef0juAMqoE",
    timestamp: "00:14:26",
    panels: 4,
    theme: "Company design — making scale feel handcrafted",
    cover: "/comics/comic_11/panel_1.webp",
  },
  {
    comic_id: "comic_12",
    slug: "comic-12",
    quote: "ChatGPT feels a little bit like MS-DOS. We haven't built Windows yet, and it will be obvious once we do.",
    speaker: "Nick Turley",
    episode_title: "Inside ChatGPT: The fastest growing product in history",
    episode_file: "nick-turley.md",
    youtube_url: "https://www.youtube.com/watch?v=ixY2PvQJ0To",
    timestamp: "00:50:07",
    panels: 4,
    theme: "AI interfaces — the Windows moment is coming",
    cover: "/comics/comic_12/panel_1.webp",
  },
  {
    comic_id: "comic_13",
    slug: "comic-13",
    quote: "I have never met this mythical beast called a great natural strategist. Great strategists have all one thing in common, they just practice.",
    speaker: "Roger Martin",
    episode_title: "5 essential questions to craft a winning strategy",
    episode_file: "roger-martin.md",
    youtube_url: "https://www.youtube.com/watch?v=y7SN4FK8noY",
    timestamp: "01:19:10",
    panels: 4,
    theme: "Strategy — there are no natural-born strategists, only practitioners",
    cover: "/comics/comic_13/panel_1.webp",
  },
  {
    comic_id: "comic_14",
    slug: "comic-14",
    quote: "Sell shit, make money.",
    speaker: "Dalton Caldwell",
    episode_title: "Lessons from 1,000+ YC startups",
    episode_file: "dalton-caldwell.md",
    youtube_url: "https://www.youtube.com/watch?v=m7LvNTbaqSI",
    timestamp: "00:04:48",
    panels: 4,
    theme: "Startup advice — cut through the BS",
    cover: "/comics/comic_14/panel_1.webp",
  },
  {
    comic_id: "comic_15",
    slug: "comic-15",
    quote: "There's always this kind of sense that the PM is not the mini CEO. How dare you call yourself that? I actually think that's exactly what the PM is.",
    speaker: "Ben Horowitz",
    episode_title: "$46B of hard truths from Ben Horowitz",
    episode_file: "ben-horowitz.md",
    youtube_url: "https://www.youtube.com/watch?v=KPxTekxQjzc",
    timestamp: "00:48:21",
    panels: 4,
    theme: "Product management — the PM is the mini CEO",
    cover: "/comics/comic_15/panel_1.webp",
  },
  {
    comic_id: "comic_16",
    slug: "comic-16",
    quote: "Before the crisis, people felt I was too involved. Once the crisis happened, people were like, 'What do we do? We need you more involved.'",
    speaker: "Brian Chesky",
    episode_title: "Brian Chesky's new playbook",
    episode_file: "brian-chesky.md",
    youtube_url: "https://www.youtube.com/watch?v=4ef0juAMqoE",
    timestamp: "00:24:55",
    panels: 4,
    theme: "Leadership — from micromanager to savior in a crisis",
    cover: "/comics/comic_16/panel_1.webp",
  },
  {
    comic_id: "comic_17",
    slug: "comic-17",
    quote: "A good pivot is like going home. It's warmer, it's closer to something that you're an expert at.",
    speaker: "Dalton Caldwell",
    episode_title: "Lessons from 1,000+ YC startups",
    episode_file: "dalton-caldwell.md",
    youtube_url: "https://www.youtube.com/watch?v=m7LvNTbaqSI",
    timestamp: "00:15:41",
    panels: 4,
    theme: "Pivoting — finding your way back to what you know",
    cover: "/comics/comic_17/panel_1.webp",
  },
  {
    comic_id: "comic_18",
    slug: "comic-18",
    quote: "Pessimism sounds extremely sophisticated. Optimism always sounds dumb — or at least naive.",
    speaker: "Tobi Lütke",
    episode_title: "Tobi Lütke's leadership playbook",
    episode_file: "tobi-lutke.md",
    youtube_url: "https://www.youtube.com/watch?v=tq6vdDJQXvs",
    timestamp: "00:22:58",
    panels: 4,
    theme: "Pessimism vs optimism — the builder always wins",
    cover: "/comics/comic_18/panel_1.webp",
  },
  {
    comic_id: "comic_19",
    slug: "comic-19",
    quote: "I pitched over a hundred investors and over a hundred investors said no. I thought the investors were wrong, frankly.",
    speaker: "Melanie Perkins",
    episode_title: "She turned 100+ rejections into a $42B company",
    episode_file: "melanie-perkins.md",
    youtube_url: "https://www.youtube.com/watch?v=-LywX3T5Scc",
    timestamp: "00:26:30",
    panels: 4,
    theme: "Persistence through rejection — Canva's origin story",
    cover: "/comics/comic_19/panel_1.webp",
  },
  {
    comic_id: "comic_20",
    slug: "comic-20",
    quote: "Most adults in the corporate environment are really just babies in disguise.",
    speaker: "Dr. Becky Kennedy",
    episode_title: "A child psychologist's guide to working with difficult adults",
    episode_file: "dr-becky-kennedy.md",
    youtube_url: "https://www.youtube.com/watch?v=Auxs8ZsHRI4",
    timestamp: "00:07:07",
    panels: 4,
    theme: "Corporate tantrums — adults behaving like toddlers",
    cover: "/comics/comic_20/panel_1.webp",
  },
  {
    comic_id: "comic_21",
    slug: "comic-21",
    quote: "Products live and die in the pixels.",
    speaker: "Nikita Bier",
    episode_title: "How to consistently go viral: Nikita Bier's playbook",
    episode_file: "nikita-bier.md",
    youtube_url: "https://www.youtube.com/watch?v=bhnfZhJWCWY",
    timestamp: "00:51:05",
    panels: 4,
    theme: "Pixel-perfect product craft beats documentation",
    cover: "/comics/comic_21/panel_1.webp",
  },
  {
    comic_id: "comic_22",
    slug: "comic-22",
    quote: "Small is not just a stepping stone. Small is a great destination itself.",
    speaker: "Jason Fried",
    episode_title: "Jason Fried challenges your thinking on fundraising, goals, growth, and more",
    episode_file: "jason-fried.md",
    youtube_url: "https://www.youtube.com/watch?v=dAnF0tk0di8",
    timestamp: "00:13:55",
    panels: 4,
    theme: "Choosing profitable and small over unicorn race",
    cover: "/comics/comic_22/panel_1.webp",
  },
  {
    comic_id: "comic_23",
    slug: "comic-23",
    quote: "Starting a company has never been easier. Scaling one has never been harder.",
    speaker: "Brian Halligan",
    episode_title: "Sequoia CEO coach: Why it's never been easier to start, never been harder to scale",
    episode_file: "brian-halligan.md",
    youtube_url: "https://www.youtube.com/watch?v=3UyitfSbY6c",
    timestamp: "00:25:54",
    panels: 4,
    theme: "Easy to start, hard to scale — the founder's journey",
    cover: "/comics/comic_23/panel_1.webp",
  },
  {
    comic_id: "comic_24",
    slug: "comic-24",
    quote: "40-60% of B2B purchases end in no decision — they just couldn't figure out how to choose.",
    speaker: "April Dunford",
    episode_title: "How to nail your product positioning",
    episode_file: "april-dunford.md",
    youtube_url: "https://www.youtube.com/watch?v=hdjlCLb9Hl8",
    timestamp: "00:22:40",
    panels: 4,
    theme: "B2B decision paralysis — the no-decision trap",
    cover: "/comics/comic_24/panel_1.webp",
  },
  {
    comic_id: "comic_25",
    slug: "comic-25",
    quote: "Give away your Legos.",
    speaker: "Molly Graham",
    episode_title: "The high-growth handbook: Molly Graham's frameworks for leading through chaos",
    episode_file: "molly-graham.md",
    youtube_url: "https://www.youtube.com/watch?v=twzLDx9iers",
    timestamp: "00:11:47",
    panels: 4,
    theme: "Delegation and growth — letting go to level up",
    cover: "/comics/comic_25/panel_1.webp",
  },
  {
    comic_id: "comic_26",
    slug: "comic-26",
    quote: "Most execution problems are actually strategy problems in disguise.",
    speaker: "Shreyas Doshi",
    episode_title: "Shreyas Doshi on pre-mortems, the LNO framework, and more",
    episode_file: "shreyas-doshi.md",
    youtube_url: "https://www.youtube.com/watch?v=Iu4Kx1jMaWU",
    timestamp: "00:54:21",
    panels: 4,
    theme: "Execution vs strategy — the hidden root cause",
    cover: "/comics/comic_26/panel_1.webp",
  },
  {
    comic_id: "comic_27",
    slug: "comic-27",
    quote: "If you ever find yourself in the comfort zone at work, you are definitely making a mistake.",
    speaker: "Matt MacInnis",
    episode_title: "Lessons from scaling Rippling",
    episode_file: "matt-macinnis.md",
    youtube_url: "https://www.youtube.com/watch?v=s848FaG8Cvs",
    timestamp: "00:05:56",
    panels: 4,
    theme: "Comfort zone is the danger zone — keep growing",
    cover: "/comics/comic_27/panel_1.webp",
  },
  {
    comic_id: "comic_28",
    slug: "comic-28",
    quote: "This is hard and I can do hard things.",
    speaker: "Dr. Becky Kennedy",
    episode_title: "A child psychologist's guide to working with difficult adults",
    episode_file: "dr-becky-kennedy.md",
    youtube_url: "https://www.youtube.com/watch?v=Auxs8ZsHRI4",
    timestamp: "01:02:09",
    panels: 4,
    theme: "Resilience — embracing difficulty as a PM",
    cover: "/comics/comic_28/panel_1.webp",
  },
  {
    comic_id: "comic_29",
    slug: "comic-29",
    quote: "I really think there is not a single person on this planet who is even close to being at their maximum potential.",
    speaker: "Tobi Lütke",
    episode_title: "Tobi Lütke's leadership playbook",
    episode_file: "tobi-lutke.md",
    youtube_url: "https://www.youtube.com/watch?v=tq6vdDJQXvs",
    timestamp: "00:08:49",
    panels: 4,
    theme: "Human potential — everyone has massive room to grow",
    cover: "/comics/comic_29/panel_1.webp",
  },
  {
    comic_id: "comic_30",
    slug: "comic-30",
    quote: "The best way to predict the future is to invent it.",
    speaker: "Bret Taylor (citing Alan Kay)",
    episode_title: "Bret Taylor on the future of careers, coding, agents, and more",
    episode_file: "bret-taylor.md",
    youtube_url: "https://www.youtube.com/watch?v=qImgGtnNbx0",
    timestamp: "01:25:05",
    panels: 4,
    theme: "Predicting vs inventing — builders shape the future",
    cover: "/comics/comic_30/panel_1.webp",
  },
  {
    comic_id: "comic_31",
    slug: "comic-31",
    quote: "A founder is an uncertainty absorber.",
    speaker: "Kunal Shah",
    episode_title: "Kunal Shah on winning in India, second-order thinking, and more",
    episode_file: "kunal-shah.md",
    youtube_url: "https://www.youtube.com/watch?v=EgBOVDzUUAA",
    timestamp: "00:35:19",
    panels: 4,
    theme: "Founder absorbs chaos so the team can stay calm",
    cover: "/comics/comic_31/panel_1.webp",
  },
  {
    comic_id: "comic_32",
    slug: "comic-32",
    quote: "If you care but don't give direct candid feedback — that's ruinous empathy.",
    speaker: "Kim Scott",
    episode_title: "Kim Scott on Radical Candor",
    episode_file: "kim-scott.md",
    youtube_url: "https://www.youtube.com/watch?v=gI0ZNhA0rvE",
    timestamp: "00:06:57",
    panels: 4,
    theme: "Ruinous empathy — nice feedback kills careers",
    cover: "/comics/comic_32/panel_1.webp",
  },
  {
    comic_id: "comic_33",
    slug: "comic-33",
    quote: "We're logic systems, but we're also heart systems and body systems and soul systems.",
    speaker: "Eoghan McCabe",
    episode_title: "How Intercom rose from the ashes by betting everything on AI",
    episode_file: "eoghan-mccabe.md",
    youtube_url: "https://www.youtube.com/watch?v=0_opWSfmN8M",
    timestamp: "01:04:24",
    panels: 4,
    theme: "Humans are not just metrics — logic, heart, body, soul",
    cover: "/comics/comic_33/panel_1.webp",
  },
];

export function getComicBySlug(slug: string): Comic | undefined {
  return comics.find((c) => c.slug === slug);
}

export function getAdjacentComics(slug: string): { prev: Comic | null; next: Comic | null } {
  const idx = comics.findIndex((c) => c.slug === slug);
  return {
    prev: idx > 0 ? comics[idx - 1] : null,
    next: idx < comics.length - 1 ? comics[idx + 1] : null,
  };
}
