// Comic metadata — sourced from comics-metadata.json
// YouTube URLs extracted from podcast transcripts + web search

export interface Comic {
  comic_id: string;
  slug: string;
  quote: string;
  speaker: string;
  episode_title: string;
  episode_file: string;
  youtube_url: string;
  timestamp: string;
  panels: number;
  theme: string;
  cover: string; // path to cover image (panel_1)
}

export const comics: Comic[] = [
  {
    comic_id: "comic_1",
    slug: "comic-1",
    quote: "Ship fast, iterate later.",
    speaker: "",
    episode_title: "",
    episode_file: "",
    youtube_url: "",
    timestamp: "",
    panels: 4,
    theme: "Kitchen cooking metaphor — shipping products fast",
    cover: "/comics/comic_1/panel_1.webp",
  },
  {
    comic_id: "comic_2",
    slug: "comic-2",
    quote: "If you can't see limitless opportunities to improve, you shouldn't be designing the product.",
    speaker: "Stewart Butterfield",
    episode_title: "Slack founder: Mental models for building products people love ft. Stewart Butterfield",
    episode_file: "stewart-butterfield.md",
    youtube_url: "https://www.youtube.com/watch?v=RP4vJeIb7WU",
    timestamp: "00:00:50",
    panels: 4,
    theme: "Woman at wardrobe — perfectionism and product craft",
    cover: "/comics/comic_2/panel_1.webp",
  },
  {
    comic_id: "comic_3",
    slug: "comic-3",
    quote: "AI is an amplifier. If you don't know what you're doing, you're just going to produce garbage faster.",
    speaker: "Lazar Jovanovic",
    episode_title: "The rise of the professional vibe coder | Lazar Jovanovic",
    episode_file: "lazar-jovanovic.md",
    youtube_url: "https://www.youtube.com/watch?v=0XNkUdzxiZI",
    timestamp: "00:00:29",
    panels: 4,
    theme: "Using phone for navigation — AI amplifying mistakes",
    cover: "/comics/comic_3/panel_1.webp",
  },
  {
    comic_id: "comic_4",
    slug: "comic-4",
    quote: "There's always data to show you that you won't be successful, but sometimes just be foolish and go ahead with it.",
    speaker: "Aishwarya Naresh Reganti",
    episode_title: "Why most AI products fail: Lessons from 50+ AI deployments | Aishwarya Naresh Reganti + Kiriti Badam",
    episode_file: "aishwarya-naresh-reganti--kiriti-badam.md",
    youtube_url: "https://www.youtube.com/watch?v=z7T1pCxgvlA",
    timestamp: "01:21:35",
    panels: 4,
    theme: "Character facing data/odds — being bold despite the numbers",
    cover: "/comics/comic_4/panel_1.webp",
  },
  {
    comic_id: "comic_5",
    slug: "comic-5",
    quote: "What matters is that the product works.",
    speaker: "Ben Horowitz",
    episode_title: "$46B of hard truths from Ben Horowitz",
    episode_file: "ben-horowitz.md",
    youtube_url: "https://www.youtube.com/watch?v=KPxTekxQjzc",
    timestamp: "00:01:12",
    panels: 4,
    theme: "Building/fixing — pragmatic product philosophy",
    cover: "/comics/comic_5/panel_1.webp",
  },
  {
    comic_id: "comic_6",
    slug: "comic-6",
    quote: "Everybody wants to talk about job loss, but what you want to look at is task loss.",
    speaker: "Marc Andreessen",
    episode_title: "Marc Andreessen: The real AI boom hasn't even started yet",
    episode_file: "marc-andreessen.md",
    youtube_url: "https://www.youtube.com/watch?v=87Pm0SGTtN8",
    timestamp: "00:00:43",
    panels: 4,
    theme: "Office scene — AI and jobs perspective",
    cover: "/comics/comic_6/panel_1.webp",
  },
  {
    comic_id: "comic_7",
    slug: "comic-7",
    quote: "The more mind-blowing it is, the more you should give it away for free.",
    speaker: "Lenny Rachitsky",
    episode_title: "Elena Verna 4.0",
    episode_file: "elena-verna-40.md",
    youtube_url: "https://www.youtube.com/watch?v=6qAB6aUMIeA",
    timestamp: "00:55:51",
    panels: 4,
    theme: "Generosity and growth — free product strategy",
    cover: "/comics/comic_7/panel_1.webp",
  },
  {
    comic_id: "comic_8",
    slug: "comic-8",
    quote: "Don't make it fake. If you don't love someone, don't tell them you love them.",
    speaker: "Jeetu Patel",
    episode_title: "AI is critical for humanity's survival | Jeetu Patel (Cisco President)",
    episode_file: "jeetu-patel.md",
    youtube_url: "https://www.youtube.com/watch?v=ylNKlBlkFas",
    timestamp: "01:02:19",
    panels: 4,
    theme: "Authenticity in relationships and product — keeping it real",
    cover: "/comics/comic_8/panel_1.webp",
  },
  {
    comic_id: "comic_9",
    slug: "comic-9",
    quote: "You should be embarrassed if your first version is not bad enough.",
    speaker: "Reid Hoffman (via Stewart Butterfield)",
    episode_title: "Slack founder: Mental models for building products people love ft. Stewart Butterfield",
    episode_file: "stewart-butterfield.md",
    youtube_url: "https://www.youtube.com/watch?v=kLe-zy5r0Mk",
    timestamp: "00:00:14",
    panels: 4,
    theme: "Perfectionism vs shipping — embracing imperfection",
    cover: "/comics/comic_9/panel_1.webp",
  },
  {
    comic_id: "comic_10",
    slug: "comic-10",
    quote: "The trick is get more people to try it, just ship things you can talk about.",
    speaker: "Lenny Rachitsky",
    episode_title: "Elena Verna 4.0",
    episode_file: "elena-verna-40.md",
    youtube_url: "https://www.youtube.com/watch?v=6qAB6aUMIeA",
    timestamp: "00:01:22",
    panels: 4,
    theme: "Growth strategy — shipping and talking about it",
    cover: "/comics/comic_10/panel_1.webp",
  },
  {
    comic_id: "comic_11",
    slug: "comic-11",
    quote: "We wanted a company where a thousand people could work, but it'll look like 10 people did it.",
    speaker: "Brian Chesky",
    episode_title: "Brian Chesky's new playbook",
    episode_file: "brian-chesky.md",
    youtube_url: "https://www.youtube.com/watch?v=4ef0juAMqoE",
    timestamp: "00:14:26",
    panels: 4,
    theme: "Company design — making scale feel handcrafted",
    cover: "/comics/comic_11/panel_1.webp",
  },
  {
    comic_id: "comic_12",
    slug: "comic-12",
    quote: "ChatGPT feels a little bit like MS-DOS. We haven't built Windows yet, and it will be obvious once we do.",
    speaker: "Nick Turley",
    episode_title: "Inside ChatGPT: The fastest growing product in history",
    episode_file: "nick-turley.md",
    youtube_url: "https://www.youtube.com/watch?v=ixY2PvQJ0To",
    timestamp: "00:00:11",
    panels: 4,
    theme: "AI interfaces — the Windows moment is coming",
    cover: "/comics/comic_12/panel_1.webp",
  },
  {
    comic_id: "comic_13",
    slug: "comic-13",
    quote: "I have never met this mythical beast called a great natural strategist. Great strategists have all one thing in common, they just practice.",
    speaker: "Roger Martin",
    episode_title: "5 essential questions to craft a winning strategy",
    episode_file: "roger-martin.md",
    youtube_url: "https://www.youtube.com/watch?v=y7SN4FK8noY",
    timestamp: "00:00:00",
    panels: 4,
    theme: "Strategy — there are no natural-born strategists, only practitioners",
    cover: "/comics/comic_13/panel_1.webp",
  },
  {
    comic_id: "comic_14",
    slug: "comic-14",
    quote: "Sell shit, make money.",
    speaker: "Dalton Caldwell",
    episode_title: "Lessons from 1,000+ YC startups",
    episode_file: "dalton-caldwell.md",
    youtube_url: "https://www.youtube.com/watch?v=m7LvNTbaqSI",
    timestamp: "00:00:04",
    panels: 4,
    theme: "Startup advice — cut through the BS",
    cover: "/comics/comic_14/panel_1.webp",
  },
  {
    comic_id: "comic_15",
    slug: "comic-15",
    quote: "There's always this kind of sense that the PM is not the mini CEO. How dare you call yourself that? I actually think that's exactly what the PM is.",
    speaker: "Ben Horowitz",
    episode_title: "$46B of hard truths from Ben Horowitz",
    episode_file: "ben-horowitz.md",
    youtube_url: "https://www.youtube.com/watch?v=KPxTekxQjzc",
    timestamp: "00:01:12",
    panels: 4,
    theme: "Product management — the PM is the mini CEO",
    cover: "/comics/comic_15/panel_1.webp",
  },
  {
    comic_id: "comic_16",
    slug: "comic-16",
    quote: "Before the crisis, people felt I was too involved. Once the crisis happened, people were like, 'What do we do? We need you more involved.'",
    speaker: "Brian Chesky",
    episode_title: "Brian Chesky's new playbook",
    episode_file: "brian-chesky.md",
    youtube_url: "https://www.youtube.com/watch?v=4ef0juAMqoE",
    timestamp: "00:00:00",
    panels: 4,
    theme: "Leadership — from micromanager to savior in a crisis",
    cover: "/comics/comic_16/panel_1.webp",
  },
  {
    comic_id: "comic_17",
    slug: "comic-17",
    quote: "A good pivot is like going home. It's warmer, it's closer to something that you're an expert at.",
    speaker: "Dalton Caldwell",
    episode_title: "Lessons from 1,000+ YC startups",
    episode_file: "dalton-caldwell.md",
    youtube_url: "https://www.youtube.com/watch?v=m7LvNTbaqSI",
    timestamp: "00:00:04",
    panels: 4,
    theme: "Pivoting — finding your way back to what you know",
    cover: "/comics/comic_17/panel_1.webp",
  },
];

export function getComicBySlug(slug: string): Comic | undefined {
  return comics.find((c) => c.slug === slug);
}

export function getAdjacentComics(slug: string): { prev: Comic | null; next: Comic | null } {
  const idx = comics.findIndex((c) => c.slug === slug);
  return {
    prev: idx > 0 ? comics[idx - 1] : null,
    next: idx < comics.length - 1 ? comics[idx + 1] : null,
  };
}
